name: mkdocs # (1)!
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yaml'
      - 'notebook/**'
      - 'docs/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV # (3)!
      - uses: actions/cache@v4
        with:
          key: BIOI611_lab-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material # (4)!
      - run: pip install jupyterlab==4.1.1 
      - run: pwd & ls
      - run: find docs/ -not -path "*.ipynb_checkpoints*" -name "*.ipynb" -exec jupyter nbconvert --to markdown --output-dir docs/ {}   \;
      - run: pwd & ls docs/
      - run: mkdocs gh-deploy --force --remote-branch gh-pages # mkdocs gh-deploy --force
